name: Build on macOS
on: push
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      run: brew install cmake

    - name: Configure
      run: cmake -B build -DEXTIT_PARANOID=ON -DEXTIT_WARNFREE=ON -DEXTIT_COMPILE_EXAMPLES=ON -DEXTIT_COMPILE_TESTS=ON

    - name: Compile
      run: cmake --build build
